### ISSUE TITLE
Pulled down latest code and seeing `Exception: Tools and tool functions are not consistent`

### ISSUE THREAD

**Issue by cfregly** [danilop/multimodal-chat#11]
```
Traceback (most recent call last):
  File "/Users/admin/dev/multimodal-chat/multimodal_chat.py", line 2576, in <module>
    main(args)
  File "/Users/admin/dev/multimodal-chat/multimodal_chat.py", line 2489, in main
    check_tools_consistency()
  File "/Users/admin/dev/multimodal-chat/multimodal_chat.py", line 1988, in check_tools_consistency
    raise Exception(f"Tools and tool functions are not consistent: {tools_set} != {tool_functions_set}")
Exception: Tools and tool functions are not consistent: {'image_catalog_count', 'notebook', 'duckduckgo_news', 'duckduckgo_text', 'wikipedia_page', 'download_image_into_catalog', 'wikipedia_search', 'duckduckgo_maps', 'retrive_from_archive', 'search_image_catalog', 'wikipedia_geodata_search', 'store_in_archive', 'generate_image', 'random_images', 'browser', 'similarity_image_catalog', 'python'} != {'image_catalog_count', 'notebook', 'duckduckgo_news', 'duckduckgo_text', 'wikipedia_page', 'download_image_into_catalog', 'wikipedia_search', 'duckduckgo_maps', 'retrive_from_archive', 'search_image_catalog', 'personal_improvement', 'wikipedia_geodata_search', 'store_in_archive', 'generate_image', 'random_images', 'browser', 'similarity_image_catalog', 'python'}
```

**Comment by cfregly** [comment]
looks like there's an issue with the new `personal_improvement` tool

```
'similarity_image_catalog', 
'personal_improvement',  # NOT MATCHING
'wikipedia_geodata_search', 
```

**Comment by cfregly** [comment]
@danilop should ./Config/tools.json include the `personal_improvement` tool?  Seems to be missing.
